spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hibernate_sequence?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: d42377878
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 20
server:
  port: 8081